<tt>
&lt;html&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;head&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;base&nbsp;href=&quot;http://fiji.sc/bugzilla/&quot;&nbsp;/&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/head&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;body&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;p&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;b&gt;&lt;a&nbsp;class=&quot;bz_bug_link&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bz_status_NEW&nbsp;&quot;<br>
&nbsp;&nbsp;&nbsp;title=&quot;NEW&nbsp;-&nbsp;python&nbsp;broke&nbsp;after&nbsp;latest&nbsp;update&quot;<br>
&nbsp;&nbsp;&nbsp;href=&quot;http://fiji.sc/bugzilla/show_bug.cgi?id=890#c1&quot;&gt;Comment&nbsp;#&nbsp;1&lt;/a&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;on&nbsp;&lt;a&nbsp;class=&quot;bz_bug_link&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bz_status_NEW&nbsp;&quot;<br>
&nbsp;&nbsp;&nbsp;title=&quot;NEW&nbsp;-&nbsp;python&nbsp;broke&nbsp;after&nbsp;latest&nbsp;update&quot;<br>
&nbsp;&nbsp;&nbsp;href=&quot;http://fiji.sc/bugzilla/show_bug.cgi?id=890&quot;&gt;bug&nbsp;890&lt;/a&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;&lt;span&nbsp;class=&quot;vcard&quot;&gt;&lt;a&nbsp;class=&quot;email&quot;&nbsp;href=&quot;mailto:aryeh&#64;cc.huji.ac.il&quot;&nbsp;title=&quot;Aryeh&nbsp;Weiss&nbsp;&lt;aryeh&#64;cc.huji.ac.il&gt;&quot;&gt;&nbsp;&lt;span&nbsp;class=&quot;fn&quot;&gt;Aryeh&nbsp;Weiss&lt;/span&gt;&lt;/a&gt;<br>
&lt;/span&gt;&lt;/b&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;pre&gt;I&nbsp;found&nbsp;the&nbsp;problem.&nbsp;<br>
The&nbsp;Libs&nbsp;for&nbsp;python&nbsp;are&nbsp;not&nbsp;brought&nbsp;in.&nbsp;<br>
If&nbsp;I&nbsp;run:<br>
<br>
import&nbsp;sys<br>
print&nbsp;sys.path<br>
<br>
We&nbsp;find:<br>
<br>
Started&nbsp;New_.py&nbsp;at&nbsp;Sun&nbsp;Aug&nbsp;10&nbsp;11:43:02&nbsp;IDT&nbsp;2014<br>
['/Applications/local/fiji/Fiji.app/jars/Lib',&nbsp;'__classpath__',<br>
'__pyclasspath__/']<br>
<br>
but&nbsp;/Applications/local/fiji/Fiji.app/jars/Lib&nbsp;does&nbsp;not&nbsp;exist.<br>
<br>
I&nbsp;downloaded&nbsp;Jython&nbsp;and&nbsp;copied&nbsp;the&nbsp;Lib&nbsp;directory&nbsp;from&nbsp;that&nbsp;package&nbsp;to&nbsp;the&nbsp;jars<br>
directory,&nbsp;and&nbsp;that&nbsp;cured&nbsp;the&nbsp;symptom.&nbsp;I&nbsp;cannot&nbsp;say&nbsp;it&nbsp;solved&nbsp;the&nbsp;problem<br>
because&nbsp;I&nbsp;still&nbsp;do&nbsp;not&nbsp;know&nbsp;why&nbsp;this&nbsp;failed&nbsp;only&nbsp;after&nbsp;the&nbsp;update&nbsp;--&nbsp;i.e.,<br>
where&nbsp;was&nbsp;the&nbsp;Lib&nbsp;before.<br>
<br>
However,&nbsp;I&nbsp;the&nbsp;gurus&nbsp;should&nbsp;be&nbsp;able&nbsp;to&nbsp;answer&nbsp;that.&lt;/pre&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/p&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;hr&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;span&gt;You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;mail&nbsp;because:&lt;/span&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;ul&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;You&nbsp;are&nbsp;the&nbsp;assignee&nbsp;for&nbsp;the&nbsp;bug.&lt;/li&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/ul&gt;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/body&gt;<br>
&lt;/html&gt;<br>

</tt>
